services:
  news-bot:
    image: news-bot
    build:
      context: .
    restart: always
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      TOKEN: ${TOKEN}
      TZ: Europe/Samara
    volumes:
      - app-data:/app/data
    networks:
      - bot-network


  news-parser:
    image: news-parser
    build:
      context: ./parsers/TG_parser/
    restart: always
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      PARSER_ID: ${PARSER_ID}
      PARSER_HASH: ${PARSER_HASH}
      AI: ${AI}
    networks:
      - bot-network

volumes:
  app-data:

networks:
  bot-network:
    driver: bridge
