services:
  news-bot:
    image: news-bot
    build:
      context: .
    restart: always
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      TOKEN: ${TOKEN}
    networks:
      - bot-network

  news-parser:
    image: news-parser
    build:
      context: ./parsers/TG_parser/
    restart: always
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      PARSER_TOKEN: ${PARSER_TOKEN}
      AI: ${AI}
    ports:
      - "80:80"
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge